#include "stdlib_float_ops.h"
#include "stdlib_helpers.h"

using namespace sgs;

void register_stdlib_float_ops(NodeRegistry *registry) {
    BEGIN_DEF("float/lerp", "Lerp", "Float")
    KEYWORDS("lerp", "mix", "linear interpolate", "blend")
    INPUT("a", "A", FLOAT, 0.0f)
    INPUT("b", "B", FLOAT, 1.0f)
    INPUT("t", "T", FLOAT, 0.5f)
    OUTPUT("result", "Result", FLOAT)
    TEMPLATE("float {result} = mix({a}, {b}, {t});")
    STAGE(STAGE_ANY) SGS_DOMAIN(DOMAIN_ALL)
    END_DEF(registry)

    BEGIN_DEF("float/clamp", "Clamp", "Float")
    KEYWORDS("clamp", "limit", "saturate")
    INPUT("x", "X", FLOAT, 0.0f)
    INPUT("min_val", "Min", FLOAT, 0.0f)
    INPUT("max_val", "Max", FLOAT, 1.0f)
    OUTPUT("result", "Result", FLOAT)
    TEMPLATE("float {result} = clamp({x}, {min_val}, {max_val});")
    STAGE(STAGE_ANY) SGS_DOMAIN(DOMAIN_ALL)
    END_DEF(registry)

    BEGIN_DEF("float/smoothstep", "Smoothstep", "Float")
    KEYWORDS("smoothstep", "smooth step", "easing")
    INPUT("edge0", "Edge0", FLOAT, 0.0f)
    INPUT("edge1", "Edge1", FLOAT, 1.0f)
    INPUT("x", "X", FLOAT, 0.5f)
    OUTPUT("result", "Result", FLOAT)
    TEMPLATE("float {result} = smoothstep({edge0}, {edge1}, {x});")
    STAGE(STAGE_ANY) SGS_DOMAIN(DOMAIN_ALL)
    END_DEF(registry)

    BEGIN_DEF("float/step", "Step", "Float")
    KEYWORDS("step", "threshold", "heaviside")
    INPUT("edge", "Edge", FLOAT, 0.5f)
    INPUT("x", "X", FLOAT, 0.0f)
    OUTPUT("result", "Result", FLOAT)
    TEMPLATE("float {result} = step({edge}, {x});")
    STAGE(STAGE_ANY) SGS_DOMAIN(DOMAIN_ALL)
    END_DEF(registry)

    BEGIN_DEF("float/saturate", "Saturate", "Float")
    KEYWORDS("saturate", "clamp01", "clamp 0 1")
    INPUT("x", "X", FLOAT, 0.0f)
    OUTPUT("result", "Result", FLOAT)
    TEMPLATE("float {result} = clamp({x}, 0.0, 1.0);")
    STAGE(STAGE_ANY) SGS_DOMAIN(DOMAIN_ALL)
    END_DEF(registry)

    BEGIN_DEF("float/remap", "Remap", "Float")
    KEYWORDS("remap", "remap range", "map range")
    INPUT("x", "X", FLOAT, 0.0f)
    INPUT("in_min", "In Min", FLOAT, 0.0f)
    INPUT("in_max", "In Max", FLOAT, 1.0f)
    INPUT("out_min", "Out Min", FLOAT, 0.0f)
    INPUT("out_max", "Out Max", FLOAT, 1.0f)
    OUTPUT("result", "Result", FLOAT)
    TEMPLATE("float {result} = {out_min} + ({x} - {in_min}) / ({in_max} - {in_min}) * ({out_max} - {out_min});")
    STAGE(STAGE_ANY) SGS_DOMAIN(DOMAIN_ALL)
    END_DEF(registry)
}
