name: CI

on:
  pull_request:
    branches: [main, release]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    uses: slice-soft/ss-pipeline/.github/workflows/ci-godot.yml@v0
    with:
      godot-version: "4.5"
      test-command: godot --headless --editor --path . --script test/runner.gd
